### PR TITLE
Fixes broken card media.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- The last update broke the card image.

# Needed By (Date)
- Soonish

# Urgency
- med/low

# Steps to Test

1. Check out this branch
2. Clear caches
3. Validate both image and video media work in the card component.

# Affected Projects or Products
- D8CORE

# Associated Issues and/or People
- D8CORE-1010

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by boznik** [comment]
i nuked and ran a fresh install. i'm getting:
Notice: Trying to get property 'height' of non-object in template_preprocess_responsive_image_formatter() (line 147 of core/modules/responsive_image/responsive_image.module).

**Comment by boznik** [comment]
Images are working as expected

**Comment by sherakama** [comment]
The field on the card paragraph is using the responsive_image_style field formatter. When a video is chosen it spits out the errors.

**Review by boznik — APPROVED** [review]
Works fine with images, but there is an issue with the field formatter when using videos.

**Comment by sherakama** [comment]
created https://stanfordits.atlassian.net/browse/D8CORE-1026

**Pull request merged**
