### PR TITLE
Updated Decanter to latest V6.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Updates Decanter to latest V6 and fixes the API breaking changes.

# Needed By (Date)
- Sooner the better or you may get broken builds

# Urgency
- Yep, please soon.

# Steps to Test

1. Check out this branch
2. run `nvm use`
3. run `npm run publish`
4. Review git for diff (should be none)
5. For bonus points, review on a live build that everything still looks good.

# Affected Projects or Products
- All the things

# Associated Issues and/or People
- 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by pookmish — CHANGES_REQUESTED** [review]
There is no command `npm run publish`

**Comment by pookmish** [comment]
Also there are changes to the templates after running `npm run build`

**Comment by sherakama** [comment]
@pookmish Publish has been added for you. You're welcome.

**Comment by pookmish** [comment]
did the twig files not update for you? I saw some pretty big differences when i ran `npm run build`

**Comment by sherakama** [comment]
They did, after I tossed out node_modules and tried again. Good catch. Yay code review.

**Review by pookmish — APPROVED** [review]

**Pull request merged**
