### PR TITLE
D8CORE-387 Dynamic layouts

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Removed all the layouts and create 3 basic ones with a configurable container option.

# Need Review By (Date)
- Turkey day

# Urgency
- medium

# Steps to Test
1. in the stack: `composer require su-sws/stanford_profile:dev-D8CORE-387-dynamic-layouts`
1. run a full site install `blt drupal:install`
1. edit the layout of a page or the content type
1. go to add a new section. verify you only get 3 options.
1. add an option and change its centered container.
1. verify it expands appropriately
1. view on of the interior pages.
1. verify there is no left sidebar
1. add a child page to the menu
1. verify it DOES have a left sidebar.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
This looks good. I just want to test the upgrade path with stanford_page as it is configured to use pacman at the moment.

**Comment by pookmish** [comment]
yay for config management. should be pretty seamless

**Comment by sherakama** [comment]
How would one deprecate these layouts? This is a pretty major removal of functionality and it is lucky we are only on an alpha release or we would have to think about that. 

Also, for modules we provide upgrade path hooks in the module.

**Comment by pookmish** [comment]
I think because we're in alpha, we can move along. not much to do at this time.
for the future, we wouldnt be able to remove a layout

**Review by sherakama — APPROVED** [review]
GTG

**Pull request merged**
