### PR TITLE
Decanter Version 6.0.1

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

Same as https://github.com/SU-SWS/jumpstart_ui/pull/17 but with the update to 6.0.1

### CODE REVIEW

**Comment by sherakama** [comment]
@boznik you're killin me here. You merged https://github.com/SU-SWS/jumpstart_ui/pull/17 without the bump.

**Comment by boznik** [comment]
i made this change on my local but didn't push it up. doh!

**Review by boznik — APPROVED** [review]
This is working as expected

**Comment by sherakama** [comment]
Thank you.

**Pull request merged**
