### PR TITLE
D8CORE-2376: Overrides local footer lockup

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Allows for overrides in the local footer lockup

# Needed By (Date)
- SEPT 4

# Urgency
- High

# Steps to Test

1. Do a full composer install/update from D8CORE-1609 of the cardinalsites repo
2. Do a drupal install (blt di)
3. Navigate to /admin/config/system/local-footer
4. Expand the local lockup settings and try out a few of the options
5. Review CSS styles

# Affected Projects or Products
- D8CORE
- SAA
- SOE

# Associated Issues and/or People
- D8CORE-2376

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
Tests are in https://github.com/SU-SWS/stanford_profile/pull/270

**Comment by jenbreese** [comment]
On the mobile view in option-a, both lines are above the line and don't match the lockup sample guide in Decanter.

**My local version:**
Screen Shot 2020-09-04 at 12 27 49 PM

**Decanter's version:**
Screen Shot 2020-09-04 at 12 28 58 PM

**Comment by sherakama** [comment]
@jenbreese Good catches. I have modified the template logic to match what is expected in the css. The lockup does require a link so I defaulted it to the front page.

**Review by jenbreese — APPROVED** [review]
Looks good. The change fixed that one thing.

**Pull request merged**
