### PR TITLE
Update to Decanter 6.0.4

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Pull in the latest styles and accessibility fixes from Decanter

# Needed By (Date)
- Thursday

# Urgency
- Med/High

# Steps to Test

1. Review code and call out anything that changed that might be off
2. Check out this branch and clear all caches
3. Visually review the following elements
* Brand Bar
* Hero Banner
* Local Footer

# Affected Projects or Products
- D8CORE

# Associated Issues and/or People
- D8CORE-1198 & D8CORE-1199
- @cjwest 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jenbreese** [comment]
@sherakama, It is missing some of the fixes. Do you want me to do it now and then again when those are ready? I'm thinking of the navigation indicator bar color fix.

**Comment by sherakama** [comment]
This has all the updates from Decanter except for the item you pushed today (button width).
https://github.com/SU-SWS/decanter/compare/6.0.4...master

I think you are thinking about the Stanford Basic repo?

**Comment by jenbreese** [comment]
Yes, I am getting the repos mixed up.

**Comment by sherakama** [comment]
@jenbreese any issues with this?

**Review by jenbreese — APPROVED** [review]
It looks right.

**Pull request merged**
